#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_Management_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AccountingDB")]
	public partial class AccountingDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertTransaction(Transaction instance);
    partial void UpdateTransaction(Transaction instance);
    partial void DeleteTransaction(Transaction instance);
    partial void InsertAuthentication(Authentication instance);
    partial void UpdateAuthentication(Authentication instance);
    partial void DeleteAuthentication(Authentication instance);
    partial void InsertProject(Project instance);
    partial void UpdateProject(Project instance);
    partial void DeleteProject(Project instance);
    partial void InsertClient(Client instance);
    partial void UpdateClient(Client instance);
    partial void DeleteClient(Client instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    #endregion
		
		public AccountingDataClassesDataContext() : 
				base(global::Accounting_Management_System.Properties.Settings.Default.AccountingDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public AccountingDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountingDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountingDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountingDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<Transaction> Transactions
		{
			get
			{
				return this.GetTable<Transaction>();
			}
		}
		
		public System.Data.Linq.Table<Authentication> Authentications
		{
			get
			{
				return this.GetTable<Authentication>();
			}
		}
		
		public System.Data.Linq.Table<Project> Projects
		{
			get
			{
				return this.GetTable<Project>();
			}
		}
		
		public System.Data.Linq.Table<Client> Clients
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Accounts")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _acc_id;
		
		private string _acc_hd;
		
		private string _rept_hd;
		
		private string _vchr_hd;
		
		private System.Nullable<double> _bill_amnt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onacc_idChanging(int value);
    partial void Onacc_idChanged();
    partial void Onacc_hdChanging(string value);
    partial void Onacc_hdChanged();
    partial void Onrept_hdChanging(string value);
    partial void Onrept_hdChanged();
    partial void Onvchr_hdChanging(string value);
    partial void Onvchr_hdChanged();
    partial void Onbill_amntChanging(System.Nullable<double> value);
    partial void Onbill_amntChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int acc_id
		{
			get
			{
				return this._acc_id;
			}
			set
			{
				if ((this._acc_id != value))
				{
					this.Onacc_idChanging(value);
					this.SendPropertyChanging();
					this._acc_id = value;
					this.SendPropertyChanged("acc_id");
					this.Onacc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc_hd", DbType="VarChar(50)")]
		public string acc_hd
		{
			get
			{
				return this._acc_hd;
			}
			set
			{
				if ((this._acc_hd != value))
				{
					this.Onacc_hdChanging(value);
					this.SendPropertyChanging();
					this._acc_hd = value;
					this.SendPropertyChanged("acc_hd");
					this.Onacc_hdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rept_hd", DbType="VarChar(50)")]
		public string rept_hd
		{
			get
			{
				return this._rept_hd;
			}
			set
			{
				if ((this._rept_hd != value))
				{
					this.Onrept_hdChanging(value);
					this.SendPropertyChanging();
					this._rept_hd = value;
					this.SendPropertyChanged("rept_hd");
					this.Onrept_hdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchr_hd", DbType="VarChar(50)")]
		public string vchr_hd
		{
			get
			{
				return this._vchr_hd;
			}
			set
			{
				if ((this._vchr_hd != value))
				{
					this.Onvchr_hdChanging(value);
					this.SendPropertyChanging();
					this._vchr_hd = value;
					this.SendPropertyChanged("vchr_hd");
					this.Onvchr_hdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bill_amnt", DbType="Float")]
		public System.Nullable<double> bill_amnt
		{
			get
			{
				return this._bill_amnt;
			}
			set
			{
				if ((this._bill_amnt != value))
				{
					this.Onbill_amntChanging(value);
					this.SendPropertyChanging();
					this._bill_amnt = value;
					this.SendPropertyChanged("bill_amnt");
					this.Onbill_amntChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transactions")]
	public partial class Transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _trans_id;
		
		private System.Nullable<System.DateTime> _trans_date;
		
		private System.Nullable<int> _donor_id;
		
		private System.Nullable<int> _rcvr_id;
		
		private System.Nullable<double> _amount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontrans_idChanging(int value);
    partial void Ontrans_idChanged();
    partial void Ontrans_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ontrans_dateChanged();
    partial void Ondonor_idChanging(System.Nullable<int> value);
    partial void Ondonor_idChanged();
    partial void Onrcvr_idChanging(System.Nullable<int> value);
    partial void Onrcvr_idChanged();
    partial void OnamountChanging(System.Nullable<double> value);
    partial void OnamountChanged();
    #endregion
		
		public Transaction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trans_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int trans_id
		{
			get
			{
				return this._trans_id;
			}
			set
			{
				if ((this._trans_id != value))
				{
					this.Ontrans_idChanging(value);
					this.SendPropertyChanging();
					this._trans_id = value;
					this.SendPropertyChanged("trans_id");
					this.Ontrans_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trans_date", DbType="Date")]
		public System.Nullable<System.DateTime> trans_date
		{
			get
			{
				return this._trans_date;
			}
			set
			{
				if ((this._trans_date != value))
				{
					this.Ontrans_dateChanging(value);
					this.SendPropertyChanging();
					this._trans_date = value;
					this.SendPropertyChanged("trans_date");
					this.Ontrans_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donor_id", DbType="Int")]
		public System.Nullable<int> donor_id
		{
			get
			{
				return this._donor_id;
			}
			set
			{
				if ((this._donor_id != value))
				{
					this.Ondonor_idChanging(value);
					this.SendPropertyChanging();
					this._donor_id = value;
					this.SendPropertyChanged("donor_id");
					this.Ondonor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rcvr_id", DbType="Int")]
		public System.Nullable<int> rcvr_id
		{
			get
			{
				return this._rcvr_id;
			}
			set
			{
				if ((this._rcvr_id != value))
				{
					this.Onrcvr_idChanging(value);
					this.SendPropertyChanging();
					this._rcvr_id = value;
					this.SendPropertyChanged("rcvr_id");
					this.Onrcvr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Float")]
		public System.Nullable<double> amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Authentication")]
	public partial class Authentication : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public Authentication()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Project")]
	public partial class Project : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prjct_id;
		
		private string _prjct_name;
		
		private string _prjct_status;
		
		private System.Nullable<double> _curr_amount;
		
		private System.Nullable<double> _prjct_exp;
		
		private System.Nullable<double> _rc_able;
		
		private System.Nullable<int> _client;
		
		private EntityRef<Client> _Client1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprjct_idChanging(int value);
    partial void Onprjct_idChanged();
    partial void Onprjct_nameChanging(string value);
    partial void Onprjct_nameChanged();
    partial void Onprjct_statusChanging(string value);
    partial void Onprjct_statusChanged();
    partial void Oncurr_amountChanging(System.Nullable<double> value);
    partial void Oncurr_amountChanged();
    partial void Onprjct_expChanging(System.Nullable<double> value);
    partial void Onprjct_expChanged();
    partial void Onrc_ableChanging(System.Nullable<double> value);
    partial void Onrc_ableChanged();
    partial void OnclientChanging(System.Nullable<int> value);
    partial void OnclientChanged();
    #endregion
		
		public Project()
		{
			this._Client1 = default(EntityRef<Client>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prjct_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int prjct_id
		{
			get
			{
				return this._prjct_id;
			}
			set
			{
				if ((this._prjct_id != value))
				{
					this.Onprjct_idChanging(value);
					this.SendPropertyChanging();
					this._prjct_id = value;
					this.SendPropertyChanged("prjct_id");
					this.Onprjct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prjct_name", DbType="VarChar(50)")]
		public string prjct_name
		{
			get
			{
				return this._prjct_name;
			}
			set
			{
				if ((this._prjct_name != value))
				{
					this.Onprjct_nameChanging(value);
					this.SendPropertyChanging();
					this._prjct_name = value;
					this.SendPropertyChanged("prjct_name");
					this.Onprjct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prjct_status", DbType="VarChar(50)")]
		public string prjct_status
		{
			get
			{
				return this._prjct_status;
			}
			set
			{
				if ((this._prjct_status != value))
				{
					this.Onprjct_statusChanging(value);
					this.SendPropertyChanging();
					this._prjct_status = value;
					this.SendPropertyChanged("prjct_status");
					this.Onprjct_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curr_amount", DbType="Float")]
		public System.Nullable<double> curr_amount
		{
			get
			{
				return this._curr_amount;
			}
			set
			{
				if ((this._curr_amount != value))
				{
					this.Oncurr_amountChanging(value);
					this.SendPropertyChanging();
					this._curr_amount = value;
					this.SendPropertyChanged("curr_amount");
					this.Oncurr_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prjct_exp", DbType="Float")]
		public System.Nullable<double> prjct_exp
		{
			get
			{
				return this._prjct_exp;
			}
			set
			{
				if ((this._prjct_exp != value))
				{
					this.Onprjct_expChanging(value);
					this.SendPropertyChanging();
					this._prjct_exp = value;
					this.SendPropertyChanged("prjct_exp");
					this.Onprjct_expChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_able", DbType="Float")]
		public System.Nullable<double> rc_able
		{
			get
			{
				return this._rc_able;
			}
			set
			{
				if ((this._rc_able != value))
				{
					this.Onrc_ableChanging(value);
					this.SendPropertyChanging();
					this._rc_able = value;
					this.SendPropertyChanged("rc_able");
					this.Onrc_ableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client", DbType="Int")]
		public System.Nullable<int> client
		{
			get
			{
				return this._client;
			}
			set
			{
				if ((this._client != value))
				{
					if (this._Client1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclientChanging(value);
					this.SendPropertyChanging();
					this._client = value;
					this.SendPropertyChanged("client");
					this.OnclientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Project", Storage="_Client1", ThisKey="client", OtherKey="client_id", IsForeignKey=true)]
		public Client Client1
		{
			get
			{
				return this._Client1.Entity;
			}
			set
			{
				Client previousValue = this._Client1.Entity;
				if (((previousValue != value) 
							|| (this._Client1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client1.Entity = null;
						previousValue.Projects.Remove(this);
					}
					this._Client1.Entity = value;
					if ((value != null))
					{
						value.Projects.Add(this);
						this._client = value.client_id;
					}
					else
					{
						this._client = default(Nullable<int>);
					}
					this.SendPropertyChanged("Client1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Client")]
	public partial class Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _client_id;
		
		private string _clent_name;
		
		private string _client_address;
		
		private string _phone_no;
		
		private string _mail;
		
		private string _client_picture;
		
		private EntitySet<Project> _Projects;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onclient_idChanging(int value);
    partial void Onclient_idChanged();
    partial void Onclent_nameChanging(string value);
    partial void Onclent_nameChanged();
    partial void Onclient_addressChanging(string value);
    partial void Onclient_addressChanged();
    partial void Onphone_noChanging(string value);
    partial void Onphone_noChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void Onclient_pictureChanging(string value);
    partial void Onclient_pictureChanged();
    #endregion
		
		public Client()
		{
			this._Projects = new EntitySet<Project>(new Action<Project>(this.attach_Projects), new Action<Project>(this.detach_Projects));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int client_id
		{
			get
			{
				return this._client_id;
			}
			set
			{
				if ((this._client_id != value))
				{
					this.Onclient_idChanging(value);
					this.SendPropertyChanging();
					this._client_id = value;
					this.SendPropertyChanged("client_id");
					this.Onclient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clent_name", DbType="VarChar(50)")]
		public string clent_name
		{
			get
			{
				return this._clent_name;
			}
			set
			{
				if ((this._clent_name != value))
				{
					this.Onclent_nameChanging(value);
					this.SendPropertyChanging();
					this._clent_name = value;
					this.SendPropertyChanged("clent_name");
					this.Onclent_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_address", DbType="VarChar(50)")]
		public string client_address
		{
			get
			{
				return this._client_address;
			}
			set
			{
				if ((this._client_address != value))
				{
					this.Onclient_addressChanging(value);
					this.SendPropertyChanging();
					this._client_address = value;
					this.SendPropertyChanged("client_address");
					this.Onclient_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_no", DbType="VarChar(50)")]
		public string phone_no
		{
			get
			{
				return this._phone_no;
			}
			set
			{
				if ((this._phone_no != value))
				{
					this.Onphone_noChanging(value);
					this.SendPropertyChanging();
					this._phone_no = value;
					this.SendPropertyChanged("phone_no");
					this.Onphone_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(50)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_picture", DbType="VarChar(MAX)")]
		public string client_picture
		{
			get
			{
				return this._client_picture;
			}
			set
			{
				if ((this._client_picture != value))
				{
					this.Onclient_pictureChanging(value);
					this.SendPropertyChanging();
					this._client_picture = value;
					this.SendPropertyChanged("client_picture");
					this.Onclient_pictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Project", Storage="_Projects", ThisKey="client_id", OtherKey="client")]
		public EntitySet<Project> Projects
		{
			get
			{
				return this._Projects;
			}
			set
			{
				this._Projects.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Projects(Project entity)
		{
			this.SendPropertyChanging();
			entity.Client1 = this;
		}
		
		private void detach_Projects(Project entity)
		{
			this.SendPropertyChanging();
			entity.Client1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _emp_id;
		
		private string _emp_name;
		
		private string _designation;
		
		private System.Nullable<System.DateTime> _joindate;
		
		private System.Nullable<double> _basic_sal;
		
		private System.Nullable<double> _receivable;
		
		private string _address;
		
		private string _phone_no;
		
		private string _mail;
		
		private string _emp_picture;
		
		private string _dept_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_idChanging(int value);
    partial void Onemp_idChanged();
    partial void Onemp_nameChanging(string value);
    partial void Onemp_nameChanged();
    partial void OndesignationChanging(string value);
    partial void OndesignationChanged();
    partial void OnjoindateChanging(System.Nullable<System.DateTime> value);
    partial void OnjoindateChanged();
    partial void Onbasic_salChanging(System.Nullable<double> value);
    partial void Onbasic_salChanged();
    partial void OnreceivableChanging(System.Nullable<double> value);
    partial void OnreceivableChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void Onphone_noChanging(string value);
    partial void Onphone_noChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void Onemp_pictureChanging(string value);
    partial void Onemp_pictureChanged();
    partial void Ondept_nameChanging(string value);
    partial void Ondept_nameChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_name", DbType="VarChar(50)")]
		public string emp_name
		{
			get
			{
				return this._emp_name;
			}
			set
			{
				if ((this._emp_name != value))
				{
					this.Onemp_nameChanging(value);
					this.SendPropertyChanging();
					this._emp_name = value;
					this.SendPropertyChanged("emp_name");
					this.Onemp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="VarChar(50)")]
		public string designation
		{
			get
			{
				return this._designation;
			}
			set
			{
				if ((this._designation != value))
				{
					this.OndesignationChanging(value);
					this.SendPropertyChanging();
					this._designation = value;
					this.SendPropertyChanged("designation");
					this.OndesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_joindate", DbType="Date")]
		public System.Nullable<System.DateTime> joindate
		{
			get
			{
				return this._joindate;
			}
			set
			{
				if ((this._joindate != value))
				{
					this.OnjoindateChanging(value);
					this.SendPropertyChanging();
					this._joindate = value;
					this.SendPropertyChanged("joindate");
					this.OnjoindateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basic_sal", DbType="Float")]
		public System.Nullable<double> basic_sal
		{
			get
			{
				return this._basic_sal;
			}
			set
			{
				if ((this._basic_sal != value))
				{
					this.Onbasic_salChanging(value);
					this.SendPropertyChanging();
					this._basic_sal = value;
					this.SendPropertyChanged("basic_sal");
					this.Onbasic_salChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receivable", DbType="Float")]
		public System.Nullable<double> receivable
		{
			get
			{
				return this._receivable;
			}
			set
			{
				if ((this._receivable != value))
				{
					this.OnreceivableChanging(value);
					this.SendPropertyChanging();
					this._receivable = value;
					this.SendPropertyChanged("receivable");
					this.OnreceivableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_no", DbType="VarChar(50)")]
		public string phone_no
		{
			get
			{
				return this._phone_no;
			}
			set
			{
				if ((this._phone_no != value))
				{
					this.Onphone_noChanging(value);
					this.SendPropertyChanging();
					this._phone_no = value;
					this.SendPropertyChanged("phone_no");
					this.Onphone_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(50)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_picture", DbType="VarChar(MAX)")]
		public string emp_picture
		{
			get
			{
				return this._emp_picture;
			}
			set
			{
				if ((this._emp_picture != value))
				{
					this.Onemp_pictureChanging(value);
					this.SendPropertyChanging();
					this._emp_picture = value;
					this.SendPropertyChanged("emp_picture");
					this.Onemp_pictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_name", DbType="VarChar(50)")]
		public string dept_name
		{
			get
			{
				return this._dept_name;
			}
			set
			{
				if ((this._dept_name != value))
				{
					this.Ondept_nameChanging(value);
					this.SendPropertyChanging();
					this._dept_name = value;
					this.SendPropertyChanged("dept_name");
					this.Ondept_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
